### ISSUE TITLE
can't install in window11

### ISSUE THREAD

**Issue by kazaff** [imagemin/imagemin-webp#44]
info run cwebp-bin@7.0.1 postinstall { code: 1, signal: null }
967 timing reify:rollback:createSparse Completed in 280ms
968 timing reify:rollback:retireShallow Completed in 0ms
969 timing command:install Completed in 19667ms
970 verbose stack Error: command failed
970 verbose stack     at ChildProcess.<anonymous> (C:\Users\ediso\AppData\Roaming\nvm\v16.14.0\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
970 verbose stack     at ChildProcess.emit (node:events:520:28)
970 verbose stack     at maybeClose (node:internal/child_process:1092:16)
970 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
971 verbose pkgid cwebp-bin@7.0.1
972 verbose cwd D:\code\test\webp-convert
973 verbose Windows_NT 10.0.22000
974 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "imagemin-webp"
975 verbose node v16.14.0
976 verbose npm  v8.3.1
977 error code 1
978 error path D:\code\test\webp-convert\node_modules\cwebp-bin
979 error command failed
980 error command C:\Windows\system32\cmd.exe /d /s /c node lib/install.js
981 error compiling from source
981 error cwebp built successfully
982 error getaddrinfo ENOENT raw.githubusercontent.com
982 error cwebp pre-build test failed
982 error D:\code\test\webp-convert\node_modules\execa\index.js:231
982 error 				err = new Error(`Command failed: ${joinedCmd}${output}`);
982 error 				      ^
982 error
982 error Error: Command failed: C:\Windows\system32\cmd.exe /s /c "./configure --disable-shared --prefix="D:\code\test\webp-convert\node_modules\cwebp-bin\vendor" --bindir="D:\code\test\webp-convert\node_modules\cwebp-bin\vendor""
982 error '.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���

982 error ���������ļ���

982 error
982 error
982 error     at D:\code\test\webp-convert\node_modules\execa\index.js:231:11
982 error     at runMicrotasks (<anonymous>)
982 error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
982 error     at async Promise.all (index 0) {
982 error   code: 1,
982 error   killed: false,
982 error   stdout: '',
982 error   stderr: "'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n���������ļ���\r\n",
982 error   failed: true,
982 error   signal: null,
982 error   cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "./configure --disable-shared --prefix="D:\\code\\test\\webp-convert\\node_modules\\cwebp-bin\\vendor" --bindir="D:\\code\\test\\webp-convert\\node_modules\\cwebp-bin\\vendor""',
982 error   timedOut: false
982 error }
983 verbose exit 1
984 timing npm Completed in 20045ms
985 verbose unfinished npm timer reify 1663225776751
986 verbose unfinished npm timer reify:build 1663225788368
987 verbose unfinished npm timer build 1663225788368
988 verbose unfinished npm timer build:deps 1663225788369
989 verbose unfinished npm timer build:run:postinstall 1663225788388
990 verbose unfinished npm timer build:run:postinstall:node_modules/cwebp-bin 1663225788389
991 verbose code 1
992 error A complete log of this run can be found in:
992 error     C:\Users\ediso\AppData\Local\npm-cache\_logs\2022-09-15T07_09_36_383Z-debug-0.log

**Comment by qwekelly** [comment]
the same error
